project_id = "luxuryloop"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[auth]
enabled = true
site_url = "https://luxury-loop.vercel.app"
additional_redirect_urls = ["https://luxury-loop.vercel.app/**", "https://luxury-loop.vercel.app/api/auth/callback"]

[auth.email]
enable_confirmations = true

[auth.email.smtp]
enabled = false

[auth.rate_limit]
email_sent = 300
token_refresh = 300
sign_up = 300

[storage]
enabled = true
file_size_limit = "50MiB"